# Generated by Django 6.0.1 on 2026-01-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
